name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a build.sh
        run: bash build.sh
        shell: bash
      - name: Archive artifacts (jar)
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-jar
          path: target/*.jar
      - name : ls
        run: |
          ls -la
          ls -la ./target
  deployment_staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: Curl a deployment
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ACCOUNT_EMAIL: ${{ secrets.ACCOUNT_EMAIL }}
          ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
        run: |
          ACCESS_TOKEN=$(curl -s -q $ENDPOINT_IAM/auth/realms/cloud-iam/protocol/openid-connect/token -d "grant_type=password&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&username=$ACCOUNT_EMAIL&password=$ACCOUNT_PASSWORD" | jq -r .access_token)
#          curl --location --request POST '$ENDPOINT_API/deployments/$DEPLOYMENT_ID/extensions/jars' \ --header 'Authorization: Bearer $ACCESS_TOKEN' \ --form 'extension=@example.jar' \ --http1.1

